version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
      platform: linux/amd64
  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
      platform: linux/amd64

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
      platform: linux/amd64

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 9.0.2
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
        CHAIN_ID: '1337'
    platform: linux/amd64

  nft_media_handler:
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 9.0.2
    platform: linux/amd64

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    platform: linux/amd64

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    platform: linux/amd64

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    platform: linux/amd64

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    platform: linux/amd64

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    platform: linux/amd64

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    platform: linux/amd64

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    platform: linux/amd64

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
